# Generated by Django 3.2.18 on 2023-04-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Diary',
        ),
    ]
