# Generated by Django 3.2.18 on 2023-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
